#+SEQ_TODO: TODO CHECK | DONE

* wishlist/status
** python
based on elpy, needs testing
*** TEST eldoc error: (void-variable virtualenv-workon-session)

hopefully fixed by 7a5b471.
** org-mode
*** DONE It looks like indentation of normal text is off
CLOSED: [2013-05-11 Sat 13:11]

This is shown at the very beginning of the line, I'm pretty sure it
used to be shown indented.

Indentation works again. Not sure why.
** calendar year view
*** not sure how to achieve this sanely
*** switching between months in calfw takes ages for me
*** issues
**** DONE Debugger entered--Lisp error: (void-function org-defvaralias)
     org-defvaralias(org-agenda-filter-preset org-agenda-tag-filter-preset)

     eval-buffer(#<buffer  *load*-351332> nil "/home/cfl/.emacs.d/site-lisp/calfw/calfw-org.el" nil t)  ; Reading at buffer position 1104
     load-with-code-conversion("/home/cfl/.emacs.d/site-lisp/calfw/calfw-org.el" "/home/cfl/.emacs.d/site-lisp/calfw/calfw-org.el" nil t)
     require(calfw-org)
     eval-buffer(#<buffer  *load*-682636> nil "/home/cfl/.emacs.d/users/cfl/init.el" nil t)  ; Reading at buffer position 2711
** speedup calfw/org calendars
** html
*** DONE all tabs
*** DONE tab is displayed as two spaces
*** TODO opening tag in single line
*** TODO wrap lines and align with first attribute of starting line
*** demonstration
#+begin_src html
  <ul>
    <li>short list item</li>
    <li>long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long long list item</li>
  </ul>
  <div>
    <p class="class1 class2 class3 class4 class5 class6 class7" name="name2">Some text</p>
  
    <p><span style="text-size: huge">Text</span></p>
  </div>
#+end_src

to be shown (but not saved ??) as

#+begin_src html
  <ul>
    <li>
      short list item
    </li>
    <li>
      long long long long long long long long long long long long
      long long long long long long long long long long long long
      long long long long long long long long long long long long
      long long long long list item
    </li>
  </ul>
  <div>
    <p class="class1 class2 class3 class4 class5 class6 class7"
       name="name1">
      Some text
    </p>
  
    <p>
      <span style="text-size: huge">
        Text
      </span>
    </p>
  </div>
#+end_src


** address book
*** what possibilities are there?
**** org-contacts
http://julien.danjou.info/projects/emacs-packages#org-contacts
- contacts as headlines with properties
- integration into message mode
- new contacts through captures

***** @coroa: how would/could that be used for notmuch address completion?
a simple
#+begin_src emacs-lisp
(require 'org-contacts (concat site-lisp-dir "/org-mode/contrib/lisp/org-contacts"))
(setq org-contacts-files '("~/notes/contacts.org"))
#+end_src
should automatically provide tab completion in message-mode of
contacts from ~/notes/contacts.org (if org-contacts-files is nil all
agenda files will be used instead).

a typical capture template would look like this (from org-contacts.el)
#+begin_src emacs-lisp
  ("c" "Contacts" entry (file "~/Org/contacts.org")
   "* %(org-contacts-template-name)
  :PROPERTIES:
  :EMAIL: %(org-contacts-template-email)
  :END:")
#+end_src

**** BBDBv3
http://savannah.nongnu.org/projects/bbdb/
- integration into message mode
- fast searching and editing through dedicated keybindings
- new contacts through dialog.
*** It feels just an org file could do it
**** grep the org file for email addresses and use these for notmuch
** Issues
*** CHECK find: `elpa/ecukes-*/ecukes': No such file or directory
make[1]: Entering directory `/home/cfl/.emacs.d/site-lisp/tagedit'
carton exec  features
make[1]: carton: Command not found
make[1]: *** [all] Error 127

**** CHECK elpa/ecukes should not be installed by elpa
try removing the directory alltogether. one can always remove
everything in there freely. it will always be pulled back in at the
next start of emacs.

@coroa: I don'd have elpa/cukes*, the error message is shown in the
first lines of make output

carton is a command line manager for elpa

ecukes is a unit/regression testing tool for emacs

all the makefile basically would do is getting all dependencies from
elpa and then run some unit tests against the code, if carton was
installed.

i would propose to ignore the warning, there is no functionality
impeded by it. alternatively i can look into packaging carton from
https://github.com/rejeep/carton.
*** DONE during org html export: run-hooks: Symbol's function definition is void: adaptive-wrap-prefix-mode
CLOSED: [2013-05-15 Wed 17:32]
this was probably due to calling on unavailable mode in html-mode-hook
(cfl). commented out.

*** CHECK magit-status destroys window layout. should be in current window?
this is a FEATURE, NOT A BUG introduced in setup-magit.el. i'm
unanimous in this regard, so i commented the respective lines out.

*** CHECK paste at point of cursor instead of mouse pointer
middle mouse click

C-h k Middle-mouse-click tells me that the function run on
middle mouse click is mouse-yank-primary, which inserts at point if
the variable mouse-yank-at-point is non-nil.

added to chaoflows config.
